//go:build !ignore_autogenerated

// Code generated manually (no kubebuilder). DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *DNSRewrite) DeepCopyInto(out *DNSRewrite) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

func (in *DNSRewrite) DeepCopy() *DNSRewrite {
	if in == nil {
		return nil
	}
	out := new(DNSRewrite)
	in.DeepCopyInto(out)
	return out
}

func (in *DNSRewrite) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DNSRewriteList) DeepCopyInto(out *DNSRewriteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DNSRewrite, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *DNSRewriteList) DeepCopy() *DNSRewriteList {
	if in == nil {
		return nil
	}
	out := new(DNSRewriteList)
	in.DeepCopyInto(out)
	return out
}

func (in *DNSRewriteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DNSRewriteSpec) DeepCopyInto(out *DNSRewriteSpec) {
	*out = *in
}

func (in *DNSRewriteSpec) DeepCopy() *DNSRewriteSpec {
	if in == nil {
		return nil
	}
	out := new(DNSRewriteSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *DNSRewriteStatus) DeepCopyInto(out *DNSRewriteStatus) {
	*out = *in
}

func (in *DNSRewriteStatus) DeepCopy() *DNSRewriteStatus {
	if in == nil {
		return nil
	}
	out := new(DNSRewriteStatus)
	in.DeepCopyInto(out)
	return out
}
